import type { NextFunction, Request, Response } from 'express';

import { db } from '../db/client';
import { deviceProfile } from '../db/schema';
import { HttpError } from './errorHandler';

/**
 * Resolves the anonymous device behind a consumer request (Phase 15).
 *
 * Three outcomes, and the middle one is the design decision worth stating:
 *
 *  - A well-formed UUID upserts a `device_profile` row and lands on
 *    `res.locals.deviceId`.
 *  - **A missing header is not an error.** Personalization is opt-in per
 *    request: a client that sends nothing gets `deviceId = null` and every
 *    downstream route answers anonymously — recommendations fall back to global
 *    popularity, the lists come back empty. Rejecting instead would make an
 *    identifier mandatory on a surface that Phase 9 deliberately built to work
 *    without one.
 *  - A *malformed* header is a 400. It is the one case where the client has
 *    stated an intent and got it wrong, and silently treating it as anonymous
 *    would hide a client bug behind a working-looking response.
 *
 * The upsert is one round trip. `onConflictDoUpdate` on the primary key turns
 * "have I seen this device" and "record that I have" into a single statement,
 * which matters because this runs ahead of every consumer request that carries
 * a device id.
 */

const DEVICE_ID_HEADER = 'x-device-id';

/**
 * RFC 4122 version-4 form, which is what the client contract specifies.
 *
 * Deliberately stricter than "any UUID": the version nibble and the variant
 * bits are checked, so an id generated by a client that is not following the
 * agreed scheme fails here rather than becoming a permanent row.
 */
const UUID_V4 = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function isValidDeviceId(value: string): boolean {
  return UUID_V4.test(value);
}

/**
 * Records that a device exists and has just been seen.
 *
 * Exported for the routes that need the row to exist before they write a child
 * row of their own (a favourite, a watch event) on a request that reached them
 * through a path where the middleware did not run.
 */
export async function touchDevice(deviceId: string): Promise<void> {
  await db
    .insert(deviceProfile)
    .values({ id: deviceId })
    .onConflictDoUpdate({ target: deviceProfile.id, set: { lastSeenAt: new Date() } });
}

export async function deviceIdentity(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  const header = req.get(DEVICE_ID_HEADER)?.trim();

  if (!header) {
    res.locals.deviceId = null;
    next();
    return;
  }

  if (!isValidDeviceId(header)) {
    // The offending value is not echoed back and not logged: it is treated as a
    // session token everywhere else, and an error message is a log line too.
    next(new HttpError(400, 'INVALID_DEVICE_ID', 'X-Device-ID must be a version 4 UUID'));
    return;
  }

  try {
    await touchDevice(header);
  } catch (error) {
    next(error);
    return;
  }

  res.locals.deviceId = header;
  next();
}

/** The device id for a request, or null when the caller sent no header. */
export function deviceIdOf(res: Response): string | null {
  return res.locals.deviceId ?? null;
}
